//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgedBook.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Publish
    {
        [Display(Name = "Publish")]
        public int PublishID { get; set; }
        [Display(Name = "User")]
        public int UserID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please select a city")]
        [Display(Name = "City")]
        public int CityID { get; set; }
        [Display(Name = "Donated")]
        public bool ActivePublish { get; set; }
        [DataType(DataType.MultilineText)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a description.")]
        public string Description { get; set; }
        [Display(Name = "ImageURL")]
        public string ImageUrl { get; set; }
        [Display(Name = "Category")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please select a category")]
        public int CategoryID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a name")]
        [Display(Name = "Name")]
        public string ItemName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
